export type Difficulty = 'Novice' | 'Intermediate' | 'Experienced' | 'Master' | 'Grandmaster' | 'Special';

export type Quest = {
  name: string;
  qp: number;
  members: boolean;
  difficulty: Difficulty;
  series?: string;
  /** Official OSRS miniquest — tracked but excluded from quest cape progress. */
  miniquest?: boolean;
  /** Recipe for Disaster subquest — tracked separately by WikiSync but counts as part of RFD. */
  rfdSubquest?: boolean;
};

/** Official OSRS miniquests (19 total). No quest points; not required for quest cape. */
export const MINIQUEST_NAMES = new Set<string>([
  'Alfred Grimhand\'s Barcrawl',
  'Barbarian Training',
  'Bear Your Soul',
  'Curse of the Empty Lord',
  'Daddy\'s Home',
  'Enter the Abyss',
  'Family Pest',
  'His Faithful Servants',
  'Hopespear\'s Will',
  'In Search of Knowledge',
  'Into the Tombs',
  'Lair of Tarn Razorlor',
  'Mage Arena I',
  'Mage Arena II',
  'Skippy and the Mogres',
  'The Enchanted Key',
  'The Frozen Door',
  'The General\'s Shadow',
  'Vale Totems',
]);

/** RFD subquests tracked by WikiSync — part of Recipe for Disaster, not separate cape quests. */
export const RFD_SUBQUEST_NAMES = new Set<string>([
  'Recipe for Disaster - Another Cook\'s Quest',
  'Recipe for Disaster - Culinaromancer',
  'Recipe for Disaster - Evil Dave',
  'Recipe for Disaster - King Awowogei',
  'Recipe for Disaster - Lumbridge Guide',
  'Recipe for Disaster - Mountain Dwarf',
  'Recipe for Disaster - Pirate Pete',
  'Recipe for Disaster - Sir Amik Varze',
  'Recipe for Disaster - Skrach Uglogwee',
  'Recipe for Disaster - Wartface & Bentnoze',
]);

export function countsTowardQuestCape(quest: Quest): boolean {
  return !quest.miniquest && !quest.rfdSubquest;
}

function applyQuestMetadata(entry: Omit<Quest, 'miniquest' | 'rfdSubquest'>): Quest {
  if (MINIQUEST_NAMES.has(entry.name)) {
    return { ...entry, miniquest: true, qp: 0 };
  }
  if (RFD_SUBQUEST_NAMES.has(entry.name)) {
    return { ...entry, rfdSubquest: true, qp: 0, series: entry.series ?? 'Recipe for Disaster' };
  }
  return entry;
}

/** Raw entries — WikiSync names with wiki quest point values before cape adjustments. */
const RAW_QUESTS: Omit<Quest, 'miniquest' | 'rfdSubquest'>[] = [
  // Free-to-play
  { name: 'Below Ice Mountain', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'Black Knights\' Fortress', qp: 3, members: false, difficulty: 'Intermediate' },
  { name: 'Cook\'s Assistant', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'Demon Slayer', qp: 3, members: false, difficulty: 'Novice', series: 'Demon Slayer' },
  { name: 'Doric\'s Quest', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'Dragon Slayer I', qp: 2, members: false, difficulty: 'Experienced', series: 'Dragonkin' },
  { name: 'Ernest the Chicken', qp: 4, members: false, difficulty: 'Novice' },
  { name: 'Goblin Diplomacy', qp: 5, members: false, difficulty: 'Novice' },
  { name: 'Imp Catcher', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'Learning the Ropes', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'Misthalin Mystery', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'Pirate\'s Treasure', qp: 2, members: false, difficulty: 'Novice' },
  { name: 'Prince Ali Rescue', qp: 3, members: false, difficulty: 'Novice', series: 'Kharidian' },
  { name: 'Romeo & Juliet', qp: 5, members: false, difficulty: 'Novice' },
  { name: 'Rune Mysteries', qp: 1, members: false, difficulty: 'Novice', series: 'Order of Wizards' },
  { name: 'Sheep Shearer', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'Shield of Arrav', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'The Corsair Curse', qp: 2, members: false, difficulty: 'Intermediate' },
  { name: 'The Ides of Milk', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'The Knight\'s Sword', qp: 1, members: false, difficulty: 'Intermediate' },
  { name: 'The Restless Ghost', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'Vampyre Slayer', qp: 3, members: false, difficulty: 'Intermediate' },
  { name: 'Witch\'s Potion', qp: 1, members: false, difficulty: 'Novice' },
  { name: 'X Marks the Spot', qp: 1, members: false, difficulty: 'Novice', series: 'Kourend' },
  // Members
  { name: 'A Kingdom Divided', qp: 2, members: true, difficulty: 'Experienced', series: 'Kourend' },
  { name: 'A Night at the Theatre', qp: 2, members: true, difficulty: 'Master' },
  { name: 'A Porcine of Interest', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'A Soul\'s Bane', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'A Tail of Two Cats', qp: 2, members: true, difficulty: 'Intermediate', series: 'Dragonkin' },
  { name: 'A Taste of Hope', qp: 1, members: true, difficulty: 'Experienced', series: 'Myreque' },
  { name: 'Alfred Grimhand\'s Barcrawl', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Animal Magnetism', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Another Slice of H.A.M.', qp: 1, members: true, difficulty: 'Intermediate', series: 'Dorgeshuun' },
  { name: 'At First Light', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Barbarian Training', qp: 1, members: true, difficulty: 'Experienced' },
  { name: 'Bear Your Soul', qp: 1, members: true, difficulty: 'Intermediate', series: 'Great Kourend quest series' },
  { name: 'Beneath Cursed Sands', qp: 2, members: true, difficulty: 'Master', series: 'Kharidian' },
  { name: 'Between a Rock...', qp: 2, members: true, difficulty: 'Experienced' },
  { name: 'Big Chompy Bird Hunting', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Biohazard', qp: 3, members: true, difficulty: 'Novice', series: 'Elf' },
  { name: 'Bone Voyage', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Cabin Fever', qp: 2, members: true, difficulty: 'Experienced', series: 'Pirate' },
  { name: 'Children of the Sun', qp: 1, members: true, difficulty: 'Novice', series: 'Twilight Emissaries' },
  { name: 'Client of Kourend', qp: 1, members: true, difficulty: 'Novice', series: 'Kourend' },
  { name: 'Clock Tower', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Cold War', qp: 1, members: true, difficulty: 'Intermediate', series: 'Penguin' },
  { name: 'Contact!', qp: 1, members: true, difficulty: 'Experienced', series: 'Kharidian' },
  { name: 'Creature of Fenkenstrain', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Current Affairs', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Curse of the Empty Lord', qp: 1, members: true, difficulty: 'Experienced', series: 'Mahjarrat' },
  { name: 'Daddy\'s Home', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Darkness of Hallowvale', qp: 2, members: true, difficulty: 'Experienced', series: 'Myreque' },
  { name: 'Death Plateau', qp: 1, members: true, difficulty: 'Novice', series: 'Troll' },
  { name: 'Death on the Isle', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Death to the Dorgeshuun', qp: 1, members: true, difficulty: 'Intermediate', series: 'Dorgeshuun' },
  { name: 'Defender of Varrock', qp: 2, members: true, difficulty: 'Experienced', series: 'Mahjarrat' },
  { name: 'Desert Treasure I', qp: 3, members: true, difficulty: 'Master', series: 'Mahjarrat' },
  { name: 'Desert Treasure II - The Fallen Empire', qp: 5, members: true, difficulty: 'Grandmaster', series: 'Mahjarrat' },
  { name: 'Devious Minds', qp: 1, members: true, difficulty: 'Experienced', series: 'Mahjarrat' },
  { name: 'Dragon Slayer II', qp: 5, members: true, difficulty: 'Grandmaster', series: 'Dragonkin' },
  { name: 'Dream Mentor', qp: 2, members: true, difficulty: 'Master' },
  { name: 'Druidic Ritual', qp: 4, members: true, difficulty: 'Novice' },
  { name: 'Dwarf Cannon', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Eadgar\'s Ruse', qp: 1, members: true, difficulty: 'Intermediate', series: 'Troll' },
  { name: 'Eagles\' Peak', qp: 2, members: true, difficulty: 'Novice' },
  { name: 'Elemental Workshop I', qp: 1, members: true, difficulty: 'Novice', series: 'Elemental Workshop' },
  { name: 'Elemental Workshop II', qp: 1, members: true, difficulty: 'Intermediate', series: 'Elemental Workshop' },
  { name: 'Enakhra\'s Lament', qp: 2, members: true, difficulty: 'Experienced', series: 'Mahjarrat' },
  { name: 'Enlightened Journey', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Enter the Abyss', qp: 1, members: true, difficulty: 'Intermediate', series: 'Order of Wizards' },
  { name: 'Ethically Acquired Antiquities', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Fairytale I - Growing Pains', qp: 2, members: true, difficulty: 'Intermediate', series: 'Fairytale' },
  { name: 'Fairytale II - Cure a Queen', qp: 2, members: true, difficulty: 'Experienced', series: 'Fairytale' },
  { name: 'Family Crest', qp: 1, members: true, difficulty: 'Experienced' },
  { name: 'Family Pest', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Fight Arena', qp: 2, members: true, difficulty: 'Intermediate', series: 'Mahjarrat' },
  { name: 'Fishing Contest', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Forgettable Tale...', qp: 2, members: true, difficulty: 'Intermediate', series: 'Red Axe' },
  { name: 'Garden of Tranquillity', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Gertrude\'s Cat', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Getting Ahead', qp: 1, members: true, difficulty: 'Intermediate', series: 'Twisted Tales' },
  { name: 'Ghosts Ahoy', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Grim Tales', qp: 1, members: true, difficulty: 'Master' },
  { name: 'Haunted Mine', qp: 2, members: true, difficulty: 'Experienced' },
  { name: 'Hazeel Cult', qp: 1, members: true, difficulty: 'Novice', series: 'Mahjarrat' },
  { name: 'Heroes\' Quest', qp: 1, members: true, difficulty: 'Experienced' },
  { name: 'His Faithful Servants', qp: 1, members: true, difficulty: 'Experienced', series: 'Mahjarrat' },
  { name: 'Holy Grail', qp: 2, members: true, difficulty: 'Intermediate', series: 'Camelot' },
  { name: 'Hopespear\'s Will', qp: 1, members: true, difficulty: 'Master' },
  { name: 'Horror from the Deep', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Icthlarin\'s Little Helper', qp: 2, members: true, difficulty: 'Intermediate', series: 'Kharidian' },
  { name: 'In Aid of the Myreque', qp: 2, members: true, difficulty: 'Intermediate', series: 'Myreque' },
  { name: 'In Search of Knowledge', qp: 1, members: true, difficulty: 'Experienced' },
  { name: 'In Search of the Myreque', qp: 2, members: true, difficulty: 'Intermediate', series: 'Myreque' },
  { name: 'Into the Tombs', qp: 1, members: true, difficulty: 'Master', series: 'Kharidian' },
  { name: 'Jungle Potion', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'King\'s Ransom', qp: 1, members: true, difficulty: 'Experienced', series: 'Camelot' },
  { name: 'Lair of Tarn Razorlor', qp: 1, members: true, difficulty: 'Experienced' },
  { name: 'Land of the Goblins', qp: 2, members: true, difficulty: 'Experienced', series: 'Dorgeshuun' },
  { name: 'Legends\' Quest', qp: 4, members: true, difficulty: 'Master' },
  { name: 'Lost City', qp: 3, members: true, difficulty: 'Intermediate' },
  { name: 'Lunar Diplomacy', qp: 2, members: true, difficulty: 'Experienced', series: 'Fremennik' },
  { name: 'Mage Arena I', qp: 1, members: true, difficulty: 'Experienced' },
  { name: 'Mage Arena II', qp: 1, members: true, difficulty: 'Master' },
  { name: 'Making Friends with My Arm', qp: 2, members: true, difficulty: 'Master', series: 'Troll' },
  { name: 'Making History', qp: 3, members: true, difficulty: 'Intermediate' },
  { name: 'Meat and Greet', qp: 1, members: true, difficulty: 'Experienced' },
  { name: 'Merlin\'s Crystal', qp: 6, members: true, difficulty: 'Intermediate', series: 'Camelot' },
  { name: 'Monk\'s Friend', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Monkey Madness I', qp: 3, members: true, difficulty: 'Master', series: 'Gnome' },
  { name: 'Monkey Madness II', qp: 4, members: true, difficulty: 'Grandmaster', series: 'Gnome' },
  { name: 'Mountain Daughter', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Mourning\'s End Part I', qp: 2, members: true, difficulty: 'Master', series: 'Elf' },
  { name: 'Mourning\'s End Part II', qp: 2, members: true, difficulty: 'Master', series: 'Elf' },
  { name: 'Murder Mystery', qp: 3, members: true, difficulty: 'Novice' },
  { name: 'My Arm\'s Big Adventure', qp: 1, members: true, difficulty: 'Experienced', series: 'Troll' },
  { name: 'Nature Spirit', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Observatory Quest', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Olaf\'s Quest', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'One Small Favour', qp: 2, members: true, difficulty: 'Experienced' },
  { name: 'Pandemonium', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Perilous Moons', qp: 2, members: true, difficulty: 'Master' },
  { name: 'Plague City', qp: 1, members: true, difficulty: 'Novice', series: 'Elf' },
  { name: 'Priest in Peril', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Prying Times', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Rag and Bone Man I', qp: 1, members: true, difficulty: 'Novice', series: 'Rag and Bone Man' },
  { name: 'Rag and Bone Man II', qp: 1, members: true, difficulty: 'Experienced', series: 'Rag and Bone Man' },
  { name: 'Ratcatchers', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Recipe for Disaster', qp: 10, members: true, difficulty: 'Special' },
  { name: 'Recipe for Disaster - Another Cook\'s Quest', qp: 1, members: true, difficulty: 'Special' },
  { name: 'Recipe for Disaster - Culinaromancer', qp: 1, members: true, difficulty: 'Special' },
  { name: 'Recipe for Disaster - Evil Dave', qp: 1, members: true, difficulty: 'Special' },
  { name: 'Recipe for Disaster - King Awowogei', qp: 1, members: true, difficulty: 'Special' },
  { name: 'Recipe for Disaster - Lumbridge Guide', qp: 1, members: true, difficulty: 'Special' },
  { name: 'Recipe for Disaster - Mountain Dwarf', qp: 1, members: true, difficulty: 'Special' },
  { name: 'Recipe for Disaster - Pirate Pete', qp: 1, members: true, difficulty: 'Special' },
  { name: 'Recipe for Disaster - Sir Amik Varze', qp: 1, members: true, difficulty: 'Special' },
  { name: 'Recipe for Disaster - Skrach Uglogwee', qp: 1, members: true, difficulty: 'Special' },
  { name: 'Recipe for Disaster - Wartface & Bentnoze', qp: 1, members: true, difficulty: 'Intermediate', series: 'Recipe for Disaster' },
  { name: 'Recruitment Drive', qp: 1, members: true, difficulty: 'Novice', series: 'Temple Knight' },
  { name: 'Regicide', qp: 3, members: true, difficulty: 'Experienced', series: 'Elf' },
  { name: 'Roving Elves', qp: 1, members: true, difficulty: 'Experienced', series: 'Elf' },
  { name: 'Royal Trouble', qp: 1, members: true, difficulty: 'Experienced', series: 'Miscellania' },
  { name: 'Rum Deal', qp: 2, members: true, difficulty: 'Experienced', series: 'Pirate' },
  { name: 'Scorpion Catcher', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Scrambled!', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Sea Slug', qp: 1, members: true, difficulty: 'Intermediate', series: 'Temple Knight' },
  { name: 'Secrets of the North', qp: 2, members: true, difficulty: 'Master', series: 'Mahjarrat' },
  { name: 'Shades of Mort\'ton', qp: 3, members: true, difficulty: 'Intermediate' },
  { name: 'Shadow of the Storm', qp: 1, members: true, difficulty: 'Intermediate', series: 'Demon Slayer' },
  { name: 'Shadows of Custodia', qp: 2, members: true, difficulty: 'Experienced' },
  { name: 'Sheep Herder', qp: 4, members: true, difficulty: 'Novice' },
  { name: 'Shilo Village', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Sins of the Father', qp: 2, members: true, difficulty: 'Master', series: 'Myreque' },
  { name: 'Skippy and the Mogres', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'Sleeping Giants', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Song of the Elves', qp: 4, members: true, difficulty: 'Grandmaster', series: 'Elf' },
  { name: 'Spirits of the Elid', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Swan Song', qp: 2, members: true, difficulty: 'Master' },
  { name: 'Tai Bwo Wannai Trio', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Tale of the Righteous', qp: 1, members: true, difficulty: 'Intermediate', series: 'Kourend' },
  { name: 'Tears of Guthix', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Temple of Ikov', qp: 1, members: true, difficulty: 'Intermediate', series: 'Mahjarrat' },
  { name: 'Temple of the Eye', qp: 1, members: true, difficulty: 'Intermediate', series: 'Order of Wizards' },
  { name: 'The Ascent of Arceuus', qp: 1, members: true, difficulty: 'Intermediate', series: 'Kourend' },
  { name: 'The Curse of Arrav', qp: 2, members: true, difficulty: 'Master', series: 'Mahjarrat' },
  { name: 'The Depths of Despair', qp: 1, members: true, difficulty: 'Intermediate', series: 'Kourend' },
  { name: 'The Dig Site', qp: 2, members: true, difficulty: 'Intermediate', series: 'Mahjarrat' },
  { name: 'The Enchanted Key', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'The Eyes of Glouphrie', qp: 2, members: true, difficulty: 'Intermediate', series: 'Gnome' },
  { name: 'The Feud', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'The Final Dawn', qp: 3, members: true, difficulty: 'Master', series: 'Twilight Emissaries' },
  { name: 'The Forsaken Tower', qp: 1, members: true, difficulty: 'Intermediate', series: 'Kourend' },
  { name: 'The Fremennik Exiles', qp: 2, members: true, difficulty: 'Master', series: 'Fremennik' },
  { name: 'The Fremennik Isles', qp: 1, members: true, difficulty: 'Experienced', series: 'Fremennik' },
  { name: 'The Fremennik Trials', qp: 3, members: true, difficulty: 'Intermediate', series: 'Fremennik' },
  { name: 'The Frozen Door', qp: 1, members: true, difficulty: 'Master' },
  { name: 'The Garden of Death', qp: 1, members: true, difficulty: 'Intermediate', series: 'Twisted Tales' },
  { name: 'The General\'s Shadow', qp: 1, members: true, difficulty: 'Experienced', series: 'Mahjarrat' },
  { name: 'The Giant Dwarf', qp: 2, members: true, difficulty: 'Intermediate', series: 'Red Axe' },
  { name: 'The Golem', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'The Grand Tree', qp: 5, members: true, difficulty: 'Intermediate', series: 'Gnome' },
  { name: 'The Great Brain Robbery', qp: 2, members: true, difficulty: 'Experienced', series: 'Pirate' },
  { name: 'The Hand in the Sand', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'The Heart of Darkness', qp: 2, members: true, difficulty: 'Experienced', series: 'Twilight Emissaries' },
  { name: 'The Lost Tribe', qp: 1, members: true, difficulty: 'Intermediate', series: 'Dorgeshuun' },
  { name: 'The Path of Glouphrie', qp: 2, members: true, difficulty: 'Experienced', series: 'Gnome' },
  { name: 'The Queen of Thieves', qp: 1, members: true, difficulty: 'Intermediate', series: 'Kourend' },
  { name: 'The Red Reef', qp: 2, members: true, difficulty: 'Experienced', series: 'Tortugan' },
  { name: 'The Ribbiting Tale of a Lily Pad Labour Dispute', qp: 1, members: true, difficulty: 'Novice' },
  { name: 'The Slug Menace', qp: 1, members: true, difficulty: 'Intermediate', series: 'Temple Knight' },
  { name: 'The Tourist Trap', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Throne of Miscellania', qp: 1, members: true, difficulty: 'Experienced', series: 'Miscellania' },
  { name: 'Tower of Life', qp: 2, members: true, difficulty: 'Novice' },
  { name: 'Tree Gnome Village', qp: 2, members: true, difficulty: 'Intermediate', series: 'Gnome quest series' },
  { name: 'Tribal Totem', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Troll Romance', qp: 2, members: true, difficulty: 'Intermediate' },
  { name: 'Troll Stronghold', qp: 1, members: true, difficulty: 'Intermediate', series: 'Troll' },
  { name: 'Troubled Tortugans', qp: 1, members: true, difficulty: 'Experienced', series: 'Tortugan' },
  { name: 'Twilight\'s Promise', qp: 1, members: true, difficulty: 'Intermediate', series: 'Twilight Emissaries' },
  { name: 'Underground Pass', qp: 5, members: true, difficulty: 'Experienced', series: 'Elf' },
  { name: 'Vale Totems', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'Wanted!', qp: 1, members: true, difficulty: 'Intermediate', series: 'Temple Knight' },
  { name: 'Watchtower', qp: 4, members: true, difficulty: 'Intermediate' },
  { name: 'Waterfall Quest', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'What Lies Below', qp: 1, members: true, difficulty: 'Intermediate' },
  { name: 'While Guthix Sleeps', qp: 5, members: true, difficulty: 'Grandmaster', series: 'Mahjarrat' },
  { name: 'Witch\'s House', qp: 4, members: true, difficulty: 'Intermediate' },
  { name: 'Zogre Flesh Eaters', qp: 1, members: true, difficulty: 'Intermediate' },
];

/** Canonical OSRS quest list — names match WikiSync; miniquests and RFD subs flagged. */
export const QUESTS: Quest[] = RAW_QUESTS.map(applyQuestMetadata);

export const CAPE_QUESTS = QUESTS.filter(countsTowardQuestCape);
export const TOTAL_CAPE_QUESTS = CAPE_QUESTS.length;
export const TOTAL_CAPE_QP = CAPE_QUESTS.reduce((sum, q) => sum + q.qp, 0);

export const QUEST_NAME_LIST = QUESTS.map((q) => q.name);
